before_all do
  sh("cd .. && chmod a+x gradlew")
end
lane :tests do
  gradle(task: "connectedAndroidTest")
  slack(slack_url: "https://hooks.slack.com/services/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",
        success: true)
end
error do |ex|
    slack(slack_url: "https://hooks.slack.com/services/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",
          success: false)
end